### ISSUE TITLE
make please dem,o 

### ISSUE THREAD

**Issue by francescogomez** [JBeutgen/Exomnium#1]
example executable for explore features on another pc without compilation

**Comment by JBeutgen** [comment]
There already is one. You can download it from

https://dl.dropboxusercontent.com/u/84900860/exomnium_sponza_release.zip

**Comment by francescogomez** [comment]
Ok, thx

**Comment by francescogomez** [comment]
@JBeutgen oh no no, my fps 

![](http://image.prntscr.com/image/95e8951a3c7a45528450db2eafa34801.png)

**Comment by JBeutgen** [comment]
Techniques like the Screen-Space Reflections unfortunately need a lot of performance.
However, I'm getting 30 fps constantly (which is the demos maximum) on my GTX 960.
Do still get 10 fps without Fraps? What does it say under the Performance tab?
